# Generated by Django 3.0.5 on 2020-05-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='champion_name',
        ),
        migrations.AddField(
            model_name='champion',
            name='championId',
            field=models.CharField(default='hm', max_length=254),
        ),
        migrations.AddField(
            model_name='champion',
            name='name',
            field=models.CharField(default='Champion', max_length=254),
        ),
    ]
