# Generated by Django 3.0.5 on 2020-05-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0002_auto_20200508_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='trait1',
            field=models.CharField(default='Blank1', max_length=254),
        ),
        migrations.AddField(
            model_name='champion',
            name='trait2',
            field=models.CharField(default='Blank2', max_length=254),
        ),
        migrations.AddField(
            model_name='champion',
            name='trait3',
            field=models.CharField(default='Blank3', max_length=254),
        ),
    ]
